[package]
name = "chia-hermes"
version = "0.1.0"
edition = "2021"

[dependencies]
clvmr = { git = "https://github.com/Chia-Network/clvm_rs", rev = "2f413e72fcf1bcafa4a3117f2c2a0a3a0e7e1c6b" }
chia-wallet-sdk = { git = "https://github.com/Rigidity/chia-wallet-sdk.git", rev = "1ee8fce668c3a81bda08a261f846671f5c8d4a33"}
